version: "3.7"

services:
  proxy:
    image: owend/certbot-nginx:0.1.0
    ports:
      - '80:80'
      - '443:443'
    environment:
      PROXY_ADDRESS: blog
      PROXY_PORT: 80
      DOMAINS: "pikach.us www.pikach.us"
    volumes:
      - ./acme:/etc/ssl/acme
    restart: always
  blog:
    image: owend/pikachus:latest
    restart: always
